# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from UI import Cylinder_design_dialog
from UI import Error_Dialog
from Model_Spawn import Elliptical

# from pythonocc_canvas.qtDisplay import qtViewer3d
# from OCC.Display.backend import load_backend
# load_backend('qt-pyqt5')
import OCC.Display.qtDisplay as qtDisplay

from Model_Spawn import cylinder
from Model_Spawn import TongTiKaiKong
from UI import  TTkaikong
from PDF_Report_spawn import PDF_Spawn_Cylinder, PDF_Spawn_TTKT

class Ui_MainWindow(object):
    def __init__(self):
        #Initialize design UI(Cylinder)
        self.disk = Cylinder_design_dialog.Ui_Dialog()
        self.Dialog_cylinder = QDialog()
        self.disk.setupUi(self.Dialog_cylinder)
        self.disk.buttonBox.accepted.connect(self.sendmsg_cylinder)
        self.disk.buttonBox.rejected.connect(self.Dialog_cylinder.rejected)
        self.parameter = {} # 模型参数

        #Initialize design UI(筒体开孔)
        self.TT = TTkaikong.Ui_Dialog()
        self.Dialog_TTKK = QDialog()
        self.TT.setupUi(self.Dialog_TTKK)
        self.TT.buttonBox.accepted.connect(self.sendmsg_TTKT)
        self.TT.buttonBox.rejected.connect(self.Dialog_TTKK.rejected)
        #self.TTKK_parameter = {}

        #Error Dialog
        self.Error_dialog = Error_Dialog.Ui_Dialog()
        self.E_Dialog = QDialog()
        self.Error_dialog.setupUi(self.E_Dialog)


        # Model Mark
        self.mark = ''


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 711)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 125))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 161, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        self.pushButton.setStyleSheet('''QPushButton{background:#F7D674;border-radius:5px;}QPushButton:hover{background:yellow;}''')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/3/openicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/3/newicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon1)
        self.pushButton_17.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.setStyleSheet('''QPushButton{background:#F76677;border-radius:5px;}QPushButton:hover{background:red;}''')
        self.gridLayout.addWidget(self.pushButton_17, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/3/saveicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet('''QPushButton{background:#6DDF6D;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(70, 80, 54, 12))
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(150, 10, 20, 70))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(170, 10, 151, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_11.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/4/o324408.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon3)
        self.pushButton_11.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_2.addWidget(self.pushButton_11, 0, 3, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_12.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/4/o324412.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon4)
        self.pushButton_12.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_2.addWidget(self.pushButton_12, 1, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/4/o324405.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/4/o324406.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_5.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/4/o324407.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon7)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_6.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../icons/4/o324409.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon8)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_7.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../icons/4/o324410.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon9)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_2.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_8.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../icons/4/o324411.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon10)
        self.pushButton_8.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_2.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(330, 10, 20, 70))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(230, 80, 54, 12))
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(360, 10, 91, 64))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_10.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../icons/6/codecalc2015_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon11)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_3.addWidget(self.pushButton_10, 0, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_18.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../icons/6/codecalcicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_18.setIcon(icon12)
        self.pushButton_18.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_18.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_3.addWidget(self.pushButton_18, 1, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_9.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../icons/6/inputtabsicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon13)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_3.addWidget(self.pushButton_9, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(370, 80, 71, 12))
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(460, 10, 20, 70))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(570, 10, 20, 70))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(690, 10, 20, 70))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(500, 80, 54, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(610, 80, 54, 12))
        self.label_7.setObjectName("label_7")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(800, 10, 20, 70))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(740, 80, 54, 12))
        self.label_8.setObjectName("label_8")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(820, 0, 221, 74))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setStyleSheet("QComboBox {"
                                    "combobox-popup: 0;\n"  # 滚动条设置必需
                                    "border-style:none; "
                                    "padding-left:10px;  "   # 字体距离左边的距离
                                    "width:48px; "
                                    "height:24px; "
                                    "font-size:12px; "
                                    "font-family:PingFangSC-Regular,PingFang SC; "
                                    "font-weight:400; "
                                    "color:rgba(93,169,255,1);\n"
                                    "line-height:24px; }\n"
                                    "QComboBox:drop-down {"  # 选择箭头样式
                                    "width:40px;  "
                                    "height:50px; "
                                    "border: none;  "
                                    "subcontrol-position: right center; "  # 位置
                                    "subcontrol-origin: padding;}\n"  # 对齐方式

                                    "QComboBox:down-arrow {"  # 选择箭头，继承drop-down
                                    "border: none; "
                                    "background: transparent; "
                                    "image: url(\"./ui/image/down.png\");}\n"

                                    "QComboBox:down-arrow:pressed { image: url(\"./ui/image/up.png\"); }\n"  # 选择箭头

                                    "QComboBox QAbstractItemView {"  # 下拉选项样式
                                    "color:black; "
                                    "background: transparent; "
                                    "selection-color:rgba(93,169,255,1);"
                                    "selection-background-color: rgba(255,255,255,1);"
                                    "}\n"
                                    
                                    "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # 滚动条样式
                                    "width: 6px;\n"
                                    "height: 100px;"
                                    "background-color: transparent;  }\n"

                                    "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # 滚动条样式
                                    "border-radius: 3px;   "
                                    "background: rgba(0,0,0,0.1);}\n"

                                    # "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # 划过滚动条，变化
                                    # "background: rgb(90, 91, 93);}\n"

                                    "QComboBox QScrollBar::add-line::vertical{"  # 滚动条上箭头
                                    "border:none;}"
                                    "QComboBox QScrollBar::sub-line::vertical{"  # 滚动条下箭头
                                    "border:none;}"
                                    "")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 1, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setStyleSheet("QComboBox {"
                                    "combobox-popup: 0;\n"  # 滚动条设置必需
                                    "border-style:none; "
                                    "padding-left:10px;  "   # 字体距离左边的距离
                                    "width:48px; "
                                    "height:24px; "
                                    "font-size:12px; "
                                    "font-family:PingFangSC-Regular,PingFang SC; "
                                    "font-weight:400; "
                                    "color:rgba(93,169,255,1);\n"
                                    "line-height:24px; }\n"
                                    
                                    "QComboBox:drop-down {"  # 选择箭头样式
                                    "width:40px;  "
                                    "height:50px; "
                                    "border: none;  "
                                    "subcontrol-position: right center; "  # 位置
                                    "subcontrol-origin: padding;}\n"  # 对齐方式

                                    "QComboBox:down-arrow {"  # 选择箭头，继承drop-down
                                    "border: none; "
                                    "background: transparent; "
                                    "image: url(\"./ui/image/down.png\");}\n"

                                    "QComboBox:down-arrow:pressed { image: url(\"./ui/image/up.png\"); }\n"  # 选择箭头

                                    "QComboBox QAbstractItemView {"  # 下拉选项样式
                                    "color:black; "
                                    "background: transparent; "
                                    "selection-color:rgba(93,169,255,1);"
                                    "selection-background-color: rgba(255,255,255,1);"
                                    "}\n"
                                    
                                    "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # 滚动条样式
                                    "width: 6px;\n"
                                    "height: 100px;"
                                    "background-color: transparent;  }\n"

                                    "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # 滚动条样式
                                    "border-radius: 3px;   "
                                    "background: rgba(0,0,0,0.1);}\n"

                                    # "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # 划过滚动条，变化
                                    # "background: rgb(90, 91, 93);}\n"

                                    "QComboBox QScrollBar::add-line::vertical{"  # 滚动条上箭头
                                    "border:none;}"
                                    "QComboBox QScrollBar::sub-line::vertical{"  # 滚动条下箭头
                                    "border:none;}"
                                    "")
        self.gridLayout_4.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.setStyleSheet("QComboBox {"
                                    "combobox-popup: 0;\n"  # 滚动条设置必需
                                    "border-style:none; "
                                    "padding-left:10px;  "   # 字体距离左边的距离
                                    "width:48px; "
                                    "height:24px; "
                                    "font-size:12px; "
                                    "font-family:PingFangSC-Regular,PingFang SC; "
                                    "font-weight:400; "
                                    "color:rgba(93,169,255,1);\n"
                                    "line-height:24px; }\n"
                                    
                                    "QComboBox:drop-down {"  # 选择箭头样式
                                    "width:40px;  "
                                    "height:50px; "
                                    "border: none;  "
                                    "subcontrol-position: right center; "  # 位置
                                    "subcontrol-origin: padding;}\n"  # 对齐方式

                                    "QComboBox:down-arrow {"  # 选择箭头，继承drop-down
                                    "border: none; "
                                    "background: transparent; "
                                    "image: url(\"./ui/image/down.png\");}\n"

                                    "QComboBox:down-arrow:pressed { image: url(\"./ui/image/up.png\"); }\n"  # 选择箭头

                                    "QComboBox QAbstractItemView {"  # 下拉选项样式
                                    "color:black; "
                                    "background: transparent; "
                                    "selection-color:rgba(93,169,255,1);"
                                    "selection-background-color: rgba(255,255,255,1);"
                                    "}\n"
                                    
                                    "QComboBox QAbstractScrollArea QScrollBar:vertical {"  # 滚动条样式
                                    "width: 6px;\n"
                                    "height: 100px;"
                                    "background-color: transparent;  }\n"

                                    "QComboBox QAbstractScrollArea QScrollBar::handle:vertical {\n"  # 滚动条样式
                                    "border-radius: 3px;   "
                                    "background: rgba(0,0,0,0.1);}\n"

                                    # "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover {\n"  # 划过滚动条，变化
                                    # "background: rgb(90, 91, 93);}\n"

                                    "QComboBox QScrollBar::add-line::vertical{"  # 滚动条上箭头
                                    "border:none;}"
                                    "QComboBox QScrollBar::sub-line::vertical{"  # 滚动条下箭头
                                    "border:none;}"
                                    "")
        self.gridLayout_4.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(900, 80, 81, 12))
        self.label_12.setObjectName("label_12")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(710, 10, 81, 64))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_13.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../icons/9/analyzeicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon14)
        self.pushButton_13.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_5.addWidget(self.pushButton_13, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_14.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../icons/9/o322498.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon15)
        self.pushButton_14.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_5.addWidget(self.pushButton_14, 0, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_15.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../icons/9/o322496.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon16)
        self.pushButton_15.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_5.addWidget(self.pushButton_15, 1, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_16.setText("")
        self.pushButton_16.setIcon(icon15)
        self.pushButton_16.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.setStyleSheet('''QPushButton{background:#FFF0F5;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.gridLayout_5.addWidget(self.pushButton_16, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget.addTab(self.tab_11, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.dockWidget_2 = QtWidgets.QDockWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setMaximumSize(QtCore.QSize(315, 524287))
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_2.setWindowTitle("")
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_2.setSizePolicy(sizePolicy)
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.dockWidgetContents_2)
        self.tabWidget_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(316, 524789))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_5.sizePolicy().hasHeightForWidth())
        self.tab_5.setSizePolicy(sizePolicy)
        self.tab_5.setObjectName("tab_5")
        self.toolBox_2 = QtWidgets.QToolBox(self.tab_5)
        self.toolBox_2.setGeometry(QtCore.QRect(0, 0, 311, 391))
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 311, 339))
        self.page_3.setObjectName("page_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 311, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setTabKeyNavigation(True)
        self.tableWidget_2.setProperty("showDropIndicator", True)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setWordWrap(True)
        self.tableWidget_2.setCornerButtonEnabled(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setVisible(True)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.toolBox_2.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 311, 339))
        self.page_4.setObjectName("page_4")
        self.tableWidget = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 311, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.toolBox_2.addItem(self.page_4, "")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_5)
        self.plainTextEdit_2.setEnabled(False)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 390, 311, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.gridLayout_7.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setRowStretch(0, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        self.gridLayout_6.addWidget(self.dockWidget_2, 1, 0, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setRowStretch(0, 1)
        self.gridLayout_6.setRowStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOutput = QtWidgets.QMenu(self.menubar)
        self.menuOutput.setObjectName("menuOutput")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOutput.menuAction())


        # python OCC UI show
        MainWindow.canva = qtDisplay.qtViewer3d(self.centralwidget)

        MainWindow.canva.setMaximumSize(10000, 10000)
        MainWindow.canva.resize(735, 550)
        MainWindow.canva.move(330, 140)
        #MainWindow.canva.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)

        # 显示设置
        MainWindow.canva.InitDriver()  # canva的驱动,设置驱动后，才能成功display
        self.display = MainWindow.canva._display
        rgb_list1 = [206, 215, 222]
        rgb_list2 = [128, 128, 128]
        self.display.set_bg_gradient_color(rgb_list1, rgb_list2)  # 设置背景渐变色
        self.display.display_triedron()  # display black trihedron

        # setAction
        self.pushButton_4.clicked.connect(self.showElliptical)
        self.pushButton_3.clicked.connect(self.design_Cylinder)
        self.pushButton_7.clicked.connect(self.design_TTkaikong)
        self.pushButton_10.clicked.connect(self.spawn_PDF_File)



        MainWindow.setWindowOpacity(0.95)
        #MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Open"))
        self.label_13.setText(_translate("MainWindow", "New"))
        self.label_3.setText(_translate("MainWindow", "File"))
        self.label_4.setText(_translate("MainWindow", "Elements"))
        self.label_5.setText(_translate("MainWindow", "Input/Output"))
        self.label_6.setText(_translate("MainWindow", "Utility"))
        self.label_7.setText(_translate("MainWindow", "Auxiliary"))
        self.label_8.setText(_translate("MainWindow", "Analyse"))
        self.label_9.setText(_translate("MainWindow", "Design Code"))
        self.label_11.setText(_translate("MainWindow", "Div.2 Class"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Division1"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Inches"))
        self.label_10.setText(_translate("MainWindow", "Units"))
        self.label_12.setText(_translate("MainWindow", "Units/Code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tools"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "3D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Diagnostics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "ESL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Help"))
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "From Node"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "To Node"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Element Type"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Diameter Basis"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Inside Diameter"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Length"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Finished Thickness"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Nominal Thickness"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Internal Corrossion All"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "External Corrosion All"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Wind Diameter Multiplier"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Material Name"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Longitudinal Seam Efficiency"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Circumferential Seam Efficiency"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "Internal Pressure"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "Temp. for Internal Pressure"))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "External Pressure"))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "Temp. for External Pressure"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_3), _translate("MainWindow", "Element Data"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Head Factor"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Inside Head Depth in                    "))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sump Head"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Parent Nozzle"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), _translate("MainWindow", "Additional Element Data"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "General Input"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Design Constraints"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Load Cases"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Wind Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOutput.setTitle(_translate("MainWindow", "Output"))

    # show Elliptical model
    def showElliptical(self):
        Elli = Elliptical.Elliptical_Head()
        A = Elli.getElliptical_Head()
        self.display.EraseAll()
        self.display.ResetView()
        self.display.DisplayShape(A.Shape(), update=True)

    # show cylinder design UI and input parameter to paint model
    def design_Cylinder(self):
        self.Dialog_cylinder.show()
        self.Dialog_cylinder.exec_()

    # show TTKT design UI and input parameter to paint model
    def design_TTkaikong(self):
        self.Dialog_TTKK.show()
        self.Dialog_TTKK.exec_()

    #Send Input Parameter to MainWindow
    def sendmsg_cylinder(self):
        R = self.disk.lineEdit_3.text() # 壳体内径
        t = self.disk.lineEdit_7.text() # 设计厚度
        L = self.disk.lineEdit_4.text() # 筒体长度
        cylinder_pressure = self.disk.lineEdit.text() #设计压力
        cylinder_temperature = self.disk.lineEdit_2.text() #设计温度
        cylinder_corrosion = self.disk.lineEdit_8.text() #腐蚀系数
        cylinder_welding = self.disk.lineEdit_9.text() #焊接系数

        if self.is_number(R) and self.is_number(t)\
                and self.is_number(L)\
                and self.is_number(cylinder_pressure)\
                and self.is_number(cylinder_temperature)\
                and self.is_number(cylinder_corrosion)\
                and self.is_number(cylinder_welding):

            self.parameter = {
                'pressure': cylinder_pressure,
                'temperature': cylinder_temperature,
                'corrosion': cylinder_corrosion,
                'welding': cylinder_welding,
                'internal_diameter': R,
                'thickness': t,
                'Length': L
            }

            R = float(R)
            t = float(t)
            L = float(L)
            C = cylinder.Cylinder(R, t, L)
            self.display.EraseAll()
            self.display.ResetView()
            C.start()
            C.join()
            self.display.DisplayShape(C.new_thing1, update=True)
            self.mark = 'cylinder'
        else:
            self.Error_dialog.label.setText("Input Error Type!")
            self.E_Dialog.show()
            self.E_Dialog.exec_()
        #self.clear_design_dialog()

    # Send Input Parameter to MainWindow
    def sendmsg_TTKT(self):
        D_i = self.TT.lineEdit.text()  # 壳内半径
        t = self.TT.lineEdit_2.text()  # 壳厚度
        l = self.TT.lineEdit_3.text()  # 筒体长度
        R_n = self.TT.lineEdit_4.text()  # 接管内半径
        L_pr1 = self.TT.lineEdit_5.text()  # 容器壁外侧接管伸出长度
        t_n = self.TT.lineEdit_6.text()  # 接管壁厚度
        t_n2 = self.TT.lineEdit_7.text()  # 变厚度接管较薄部分公称厚度
        t_e = self.TT.lineEdit_8.text()  # 补强板厚度
        L_pr2 = self.TT.lineEdit_9.text()  # 容器壁内侧接管伸出长度
        L_pr3 = self.TT.lineEdit_10.text()  # 外侧变厚度t的长度
        P = self.TT.lineEdit_11.text()  # 设计压力
        T = self.TT.lineEdit_12.text()  # 设计温度
        C_2 = self.TT.lineEdit_13.text()  # 壳体腐蚀裕量
        C_2t = self.TT.lineEdit_14.text()  # 接管腐蚀裕量
        W = self.TT.lineEdit_15.text()  # 补强板宽度
        L_42 = self.TT.lineEdit_16.text()  # 补强板焊制容器焊脚长度
        L_43 = self.TT.lineEdit_17.text()  # 内测接管填角焊缝的焊脚长度
        R_nc = self.TT.lineEdit_18.text()  # 容器上沿接管开口方向接管半径
        E = self.TT.lineEdit_19.text()  # 焊接接头系数
        thita = self.TT.lineEdit_20.text()  # 接管轴线与筒体表面法线夹角

        if self.is_number(D_i) and self.is_number(t)\
            and self.is_number(l) and self.is_number(R_n)\
            and self.is_number(L_pr1) and self.is_number(t_n)\
            and self.is_number(t_n2) and self.is_number(t_e)\
            and self.is_number(L_pr2) and self.is_number(L_pr3)\
            and self.is_number(P) and self.is_number(T)\
            and self.is_number(C_2) and self.is_number(C_2t)\
            and self.is_number(W) and self.is_number(L_42)\
            and self.is_number(L_43) and self.is_number(R_nc)\
            and self.is_number(thita):

            self.parameter = {'shell_internal_radius': D_i,
                                   'shell_thickness': t,
                                   'cylinder_length': l,
                                   'pipe_internal_radius': R_n,
                                   'pipe_out_length': L_pr1,
                                   'pipe_thickness': t_n,
                                   'nominal_thickness': t_n2,
                                   'plate_thickness': t_e,
                                   'pipe_in_length': L_pr2,
                                   'out_thickness_length': L_pr3,
                                   'pressure': P,
                                   'temperature': T,
                                   'shell_corrosion': C_2,
                                   'pipe_corrosion': C_2t,
                                   'plate_width': W,
                                   'L_42': L_42,
                                   'L_43': L_43,
                                   'R_nc': R_nc,
                                   'E': E,
                                   'thita': thita}

            D_i = float(D_i)
            t = float(t)
            l = float(l)
            R_n = float(R_n)
            L_pr1 = float(L_pr1)
            t_n = float(t_n)
            t_n2 = float(t_n2)
            t_e = float(t_e)
            L_pr2 = float(L_pr2)
            L_pr3 = float(L_pr3)
            tongtikaikong = TongTiKaiKong.TTKaikong(D_i, t, l, R_n, L_pr1, t_n, t_n2, t_e, L_pr2, L_pr3)
            self.display.EraseAll()
            self.display.ResetView()
            tongtikaikong.start()
            tongtikaikong.join()
            print("Error input")
            self.display.DisplayShape(tongtikaikong.new_thing0, update=True)
            self.mark = 'TTKT'
        else:
            self.Error_dialog.label.setText("Input Error Type!")
            self.E_Dialog.show()
            self.E_Dialog.exec_()
        #self.clear_design_dialog()

    #Clear Design UI after Inputing
    def clear_design_dialog(self):
        self.disk.lineEdit_4.setText("")
        self.disk.lineEdit_7.setText("")
        self.disk.lineEdit_3.setText("")
        self.disk.lineEdit.setText("")
        self.disk.lineEdit_2.setText("")
        self.disk.lineEdit_8.setText("")
        self.disk.lineEdit_9.setText("")
        self.TT.lineEdit.setText("")
        self.TT.lineEdit_2.setText("")
        self.TT.lineEdit_3.setText("")
        self.TT.lineEdit_4.setText("")
        self.TT.lineEdit_5.setText("")
        self.TT.lineEdit_6.setText("")
        self.TT.lineEdit_7.setText("")
        self.TT.lineEdit_8.setText("")
        self.TT.lineEdit_9.setText("")
        self.TT.lineEdit_10.setText("")

    #judge a input whether is a number
    def is_number(self, a):
        if a.replace('.', '').isdigit():
            return True
        return False

    # spawn cylinder report
    def spawn_PDF_File_Report_Cylinder(self):
        if self.parameter != {}:
            pdf_generator = PDF_Spawn_Cylinder.PDFGenerator(self.parameter)
            pdf_generator.genTaskPDF()
        else:
            self.Error_dialog.label.setText("There is no input!")
            self.E_Dialog.show()
            self.E_Dialog.exec_()

    # spawn TTKT report
    def spawn_PDF_File_Report_TTKT(self):
        if self.parameter != {}:
            pdf_generator = PDF_Spawn_TTKT.PDFGenerator(self.parameter)
            pdf_generator.genTaskPDF()
        else:
            self.Error_dialog.label.setText("There is no input!")
            self.E_Dialog.show()
            self.E_Dialog.exec_()

    def spawn_PDF_File(self):
        switch = {'cylinder': self.spawn_PDF_File_Report_Cylinder,
                       'TTKT': self.spawn_PDF_File_Report_TTKT}
        switch.get(self.mark, self.default)()
        self.mark = ''

    def default(self):
        self.Error_dialog.label.setText("There is no model!")
        self.E_Dialog.show()
        self.E_Dialog.exec_()